[Feat/#13] 제품 상세 페이지 UI 구현
SOPT-all/35-COLLABORATION-ANDROID-DAANGN pull request #18
Opened 2024-11-25 18:53 UTC by angryPodo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #13 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- 탑바 뒤로가기 누르면 검색화면으로 이동
- 탑바 홈버튼 누르면 EX1화면으로 이동(이건 홈화면 구현시 나중에 연결)
- 탑바 스크롤시 색상 변화 추가함~~!!!

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/0c839274-bb3b-4979-b17d-ce08523cbd1c

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
- 관련된 API 서비스랑 DTO는 구현만 해놨습니다.
- 최대한 Screen에 담기는 인자 최소화 했습니다.
- viewModel은 아직 하는게 없습니다.

2024-11-26 21:51 UTC, wjdrjs00 approved these changes
제품 화면 구현! 고생하셨습니다!!
UI위주로 확인했고, 추후 서버 연결 작업 시 변경 가능성 있는 부분들은 서버 작업 이후에 좀 더 자세하게 리뷰해보겠습니다!👍🏻

2024-11-26 21:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                modifier = Modifier.zIndex(1f).background(backgroundColor)
p3: 줄바꿈 한번 부탁드립니다!👨🏻‍🌾
```suggestion
                modifier = Modifier
                            .zIndex(1f)
                            .background(backgroundColor)
```

2024-11-26 21:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +                }
p3: 동일한 간격이라면 이렇게도 구현하는 방법도 있습니다!!
```suggestion
                Row(
                    modifier = Modifier,
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    Text(
                        text = userInfo.nickname,
                        style = CarrotTheme.typography.body.b_18,
                        color = CarrotTheme.colors.gray8
                    )
                    VerticalDivider(
                        modifier = Modifier.height(10.dp),
                        thickness = 1.dp
                    )
                    Text(
                        text = "5시간 전 접속",
                        style = CarrotTheme.typography.body.md_13_18_013,
                        color = CarrotTheme.colors.gray5
                    )
                }
```

2024-11-26 21:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +                        .offset(x = (-1).dp, y = (-1).dp)
p2: 이 부분 제 뷰에서는 피그마에 정의된 크기를 활용하면 추가적인 위치나 size설정 없이 구현 가능했던거 같아서 남겨봅니다!!

2024-11-26 21:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RelatedProductSection.kt
> +                .aspectRatio(181f / 136f)  // 비율은 유지
p5: aspectRatio 이건 처음보는건데 어떤건지 설명해주세요👨🏻‍🌾🙇🏻‍♂️!!

2024-11-26 21:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductInfoSection.kt
> +                )
p2: 이 부분 하나의 text 컴포넌트로도 가능할 듯 싶습니다!! 그치만 개인취향인거 같기도 합니다!! style와 color의 값이 동일해서 한번 스윽 남겨봅니다!!

2024-11-26 21:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductBottomBar.kt
> +            Color(0xFFFF4F4F) // 빨간색으로 설정
p3: 이렇게 하면 주석 없어도 이해가 될거 같습니다!! (그냥 간단한 다른방법도 있다 느낌?)
```suggestion
            Color.Red
```

2024-11-27 08:33 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductInfoSection.kt
> +                )
저도 한꺼번에 하려니까 중간에 있는 기호만 밑줄이 없더라구요..
```kotlin
Text(
    text = buildAnnotatedString {
        withStyle(
            SpanStyle(textDecoration = TextDecoration.Underline)
        ) {
            append(productInfo.category)
        }
        append(" . ")  // 밑줄 없는 부분
        withStyle(
            SpanStyle(textDecoration = TextDecoration.Underline)
        ) {
            append("끌올 ${productInfo.view}시간 전")
        }
    },
    style = CarrotTheme.typography.caption.md_14_028,
    color = CarrotTheme.colors.gray5
)
```
하나로 묶으려면 이정도로 할수 있을것 같은데 어떤게 좋아보이시나요!

2024-11-27 08:34 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                modifier = Modifier.zIndex(1f).background(backgroundColor)
적용했습니다!!

2024-11-27 08:37 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductBottomBar.kt
> +            Color(0xFFFF4F4F) // 빨간색으로 설정
적용했습니다!

2024-11-27 08:37 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +                        .offset(x = (-1).dp, y = (-1).dp)
요 부분도 오프셋 빼도 되더라구요? 박스 정렬이랑 겹칠까봐 넣었었는데ㅠ

2024-11-27 08:39 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +                }
이 부분도 적용했ㅅ브니다!

2024-11-27 08:42 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RelatedProductSection.kt
> +                .aspectRatio(181f / 136f)  // 비율은 유지
음 예를들어서 그리드나 리스트에 있는 이미지의 크기가 고정이 아니고 기기대응이 되는 부분에 적용 할수 있어요. 예를 들어서 디자인이 1920x1440비율을 유지하면 좋겠다고 했을때, 가로세로 크기를 고정시키지 않고 비율로 주는 방법입니다! 버튼이나 텍스트 뺴고는 많이 사용하는것 같아요

2024-11-27 10:52 UTC, hyoeunjoo requested changes
진짜 민재당근.. ㅠㅠ 디테일한 부분들 신경써주느냐 너무너무너무 고생햇다링..ㅠㅠㅠ
고정 dp주는거 살짝 바꿔주면 조을거가타요!! 그리구 서버 부분은 dto 형식만 살짝 수정해주고 나머지는 다음 브랜치에서 적용하는걸루 합시다!!

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/data/model/response/ProductDetailResponse.kt.kt
> +
p1: 이제 이 부분은 BaseResponse가 있어서 삭제해주셔도 됩니다 ㅎㅎ

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/data/model/response/ProductDetailResponse.kt.kt
> +data class ProductInfo(
p1: ResponseDummyDto와 같이 네이밍은 앞으로 ResponseProductInfoDto 이런식으로 변경하도록 할게요!

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/data/service/ProductApiService.kt
> +    ): Response<ProductDetailResponse>
p2: 이제 여기의 Response를 BaseResponse로 감싸주면 됩니다. 근데 일단은 이 브랜치에서는 DTO 네이밍 수정과 반복되는 Response삭제하는 것으로 할게요!

반복되는 Response는 아래와 같은 형식을 얘기한 것입니다~
```
@Serializable
data class UserResponse(
    @SerialName("status")
    val status: Int,
    @SerialName("result")
    val result: UserInfo
)
```

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                    }
p1: 여기 horizontal 16.dp로 모두 안주고 맨 위에서 한 번만 줘도 좋을 것 같아요~

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +    val onBackClick = { navController.navigate(ScreenRoutes.TITLE_SEARCH) }
p2: 해당 productDetailScreen은 SearchScreen에서 오는거죵? 그렇다면 BackClick의 의도에 맞게 navigate가 아닌 popstack을 사용해주시는게 더 맞을 것 같아용. 그게 스택도 안쌓이구요

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +    )
p1: 우와 신기 ㄷㄷ 야무지다 이런 디테일까지..! 최고당근 ㅠㅠ근데 제가 실행해본결과 투명 -> 흰색 전환은 잘 되는데 당근 앱처럼 뭔가    부드럽게 투명도가 사라지면서 적용되지는 않더라구요. 약간 확확 바뀌는 그런 느낌..??
그래서 제가 따로 한 번 찾아봤는데요. 이게 좋은 방법인지는 모루갯다만...

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +    )
p1 : 여기서 색을 Transparent, White로 바로 설정하는게 아니라 alpha값을 줘서 투명도를 조절했습니다.
또한 속도를 조금 더 늦춰서 천천히 변경되게끔 했습니다.

```
    val backgroundColor by animateColorAsState(
        targetValue = if (isScrolledPastImage) Color.White.copy(alpha = 1f) else Color.White.copy(alpha = 0f),
        animationSpec = tween(durationMillis = 800),
        label = ""
    )
```
이렇게 하면 조금 더 자연스러운 것 같더라구요?

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                modifier = Modifier.zIndex(1f).background(backgroundColor)
![image](https://github.com/user-attachments/assets/e4acbcba-ce43-4803-8e36-15b4a755bc39)
![image](https://github.com/user-attachments/assets/77ac2ea6-3350-4451-8b43-3e9fbb3b3137)

이거 실제 당근 들어가서 캡쳐온건데 살짝 아이콘 아래부분에 패딩을 주시면 좋을 것 같아요 지금은 너무 끝과 아이콘이 붙어있는 느낌이더라구용 피그마엔 따로 없으니..ㅋㅜ 눈대중으로..아시져? 알잘딱깔센 ㅋㅋ

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailViewModel.kt
> +
p3: 이거 mapper구현하신 것 같아용 맞을까요? 이제 이 부분 그 제가 보내드린 글 보시고 바꿔주시면 될 듯 합니다!! 이건 다음 브랜치에서 하는걸루 하죵! 그래서 p3!

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +
우앙 디테일 ㅋㅋ

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +        verticalArrangement = Arrangement.spacedBy(28.dp)
p1: 이 부분은 spacedBy를 쓰신 이유가 있을까용?

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +                        style = CarrotTheme.typography.body.b_14
p1: text들은 string 추출해주세요!

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +                    horizontalArrangement = Arrangement.spacedBy(8.dp),
p1: 요기두! spacedBy 쓰신 이유가 궁금해용

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductBottomBar.kt
> +        shape = RoundedCornerShape(4.dp)
p1: 고정 dp값은 최대한 피해주시는게 좋습니다! width와 height를 직접적으로 주기보다는 text를 담고있는 button의 contentPadding에서 vertical 8.dp horizontal=14.dp 뭐 이렇게 주시면 조금 더 유연한 ui가 될 것 같다는 생각이 드네요!!

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductInfoSection.kt
> +                    textDecoration = TextDecoration.Underline,
p4: 이 부분은 view로 일단 데이터를 넣어놓으신걸까용?

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductTopBar.kt
> +
헉 미쳤다.....ㅠㅠ 정성..

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductTopBar.kt
> +            .padding(horizontal = 16.dp),
p1: 고정dp..! 그리구 아까 위에 적었는데 이 부분 bottom에 살짝 패딩 주면 되겟네용!!?

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RecommendProductSection.kt
> +                .heightIn(max = 700.dp)
p3: heightIn은 어떤건가용? 우와

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RelatedProductSection.kt
> +            title = "이렇게 제목이 길어지면 니가 뭘 할 수 있는데 이 자식아 ${it + 1}",
어쩔건뎅 ㅋㅋ

2024-11-27 10:52 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +            Column(
p1: 이 부분도 위에서 말했던 것처럼..!! Row가 Column을 가지구 있으니까, 그 안에 있는 Column의 vertical로 상하 15.dp를 주면 될 것 같다는 생각이 드는데용??

2024-11-27 11:15 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RelatedProductSection.kt
> +                .aspectRatio(181f / 136f)  // 비율은 유지
호오 새롭게 배워갑니다!

2024-11-27 11:37 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductInfoSection.kt
> +                )
저도 추가로 알아보니 buildAnnotatedString를 활용한 방법이 하나의 text컴포저블만을 사용해서 좀 더 랜더링 성능상 이점이 있다고 합니다.(처음은 컴포지션이 3개지만 후자는 1개이기 때문이라고 합니다!)

2024-11-27 13:57 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +        verticalArrangement = Arrangement.spacedBy(28.dp)
divider때문에 넣어놨어요. 하나로 묶어서 상하 패딩 줄거면 spacedBy로 하는게 좋을까? 해서 넣어놨는데 이런경우에 그냥 Spacer로 패딩주거나 컴포즈함수에 패딩을 주는게 보편적일까요?

2024-11-27 13:59 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +                    horizontalArrangement = Arrangement.spacedBy(8.dp),
여기도 아이콘이랑 텍스트 사이에 패딩을 줘야 하는데 Spacer를 써도 되나? 싶어가지고 저렇게 패딩값을 줬습니다!

2024-11-27 14:03 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductInfoSection.kt
> +                    textDecoration = TextDecoration.Underline,
이 부분은 서버에서 오는 응답이 아니어서 하드코딩으로 넣을까 했으나 그래도 목록마다 달라지는걸 구현하고자 서버에서 오는 응답중 view를 활용하려고 일단 넣어놨어요. 지금 보니까 조회수가 24시간이 넘어가는게 꽤 있어서 그부분 예외 처리 해주면 좋을 것 같은데 어떨까요!

2024-11-27 14:39 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RecommendProductSection.kt
> +                .heightIn(max = 700.dp)
heightIn()은 컴포저블의 높이를 최소(min)와 최대(max) 값으로 제한합니다! 700이하에 Lazy였다면 컨텐츠 자체가 줄어들어 스크롤도 안대구요! 저부분은 기기대응으로 생각했을때 섹션이 너무 커지는걸 제한하려고 뒀던 옵션이에요

2024-11-27 14:45 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +            Column(
이 부분은 혹시 어떤 곳 15값 말씀하시는 걸까요...!! 만약에 아래 사진에서 상하 패딩을 말씀하시는거면 Row에 Row두개를 배치한거라서 부모 Row에 상하 16을 줬어요. 이 부분을 수정하는걸까요?
<img width="323" alt="image" src="https://github.com/user-attachments/assets/fce3ef71-6f94-48ab-93b7-f17d60a68b45">

2024-11-27 15:15 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/data/service/ProductApiService.kt
> +    ): Response<ProductDetailResponse>
요 부분도 네이밍 바꾸면서 래핑했습니다!

2024-11-27 15:15 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                    }
여기는 ProductImageSection때문에 제가 아는 방법으로는 어쩔 수 없나바요..

2024-11-27 15:16 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +    val onBackClick = { navController.navigate(ScreenRoutes.TITLE_SEARCH) }
popStack으로 수정했습니다!

2024-11-27 15:17 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +    )
tween이녀석이 핵심이던데 어려워서 자세하게 까지는 구현 못했어요ㅜ 그리고 확실히 에뮬상에서 테스트랑 실기기 테스트에 차이가 있어서 딜레이 면에서 놓치는게 있는데 꼼꼼하게 하겠습니다!!!

2024-11-27 15:17 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                modifier = Modifier.zIndex(1f).background(backgroundColor)
짝수 dp로 해치워버림

2024-11-27 15:18 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailViewModel.kt
> +
네! 임시로 구현해놨던건데 다음 서버통신 브랜치에서 작업하겠ㅅ브니다!

2024-11-27 15:48 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/ProductTopBar.kt
> +            .padding(horizontal = 16.dp),
해결!!!

2024-11-27 16:15 UTC, hyoeunjoo reviewed
고생이 많당..............................................................................................................근

2024-11-27 16:15 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +                    }
고생하셨어요...

2024-11-27 16:15 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +                modifier = Modifier.weight(1f),
weight도 막 사용하고!! 점점 더 잘한다!!

2024-11-27 16:15 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/KeywordAlertSection.kt
> +                    horizontalArrangement = Arrangement.spacedBy(8.dp),
아항 저같은 경우에는 아이콘안에 modifier.padding(end)로 줬을 것 같아요!

2024-11-27 16:15 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/RecommendProductSection.kt
> +                .heightIn(max = 700.dp)
오오!!!!! 그렇군요!

2024-11-27 16:15 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/components/UserInfoSection.kt
> +            Column(
아하ㅠㅠ 제가 말을 좀 두서없이 했네요..!! 그 height 48.dp로 주신 부분을 바꾸면 좋겠다는 뜻이었어요!!
지금 부모 row에 상하로 padding을 잘 주셨네요!! 그러면 유저온도 부분은 row로 한 번 묶어서 topend에 붙이면 굳이 height 48로 높이를 설정해줄 필요가 없을 것 같아서요! (아니라면 언제든지 반박가능)

2024-11-27 17:10 UTC, hyoeunjoo approved these changes
하...드디어 때가 왔습니다..... "머지"하십쇼....

2024-11-27 18:08 UTC, merged