[Feat/#15] 판매자 프로필 화면 UI 구현
SOPT-all/35-COLLABORATION-ANDROID-DAANGN pull request #20
Opened 2024-11-26 21:41 UTC by wjdrjs00

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- [x] merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- [x] 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- [x] 리뷰는 (아직 미정)에 진행됩니다.
- [x] P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- [x] Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #15 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- 판매자 프로필 화면 UI 구현
- 팔로우 확인 다이얼로그 UI 기능 구현

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁
https://github.com/user-attachments/assets/02961ceb-68d3-4446-9436-a0ac23779ea1

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
- 이번 작업에서는 UI 구현 위주로 진행했습니다!!
- viewmodel은 아직 구현 안했습니다!! 추후 서버와 연결 작업하며 보강해보겠습니다! 🥕
  - 서버 연결하면서 전반적인 수정(필요한 것만 스틀링 추출하고 나머지는 서버에서 받는다는 컨셉으로 수정)해보겠습니다!

2024-11-27 13:08 UTC, hyoeunjoo requested changes
고생했당근!!!ㅠㅠ 이제 얼마 안남았다 좀만 홧팅!!
글고 string 추출은 꼭 해주세요오

2024-11-27 13:08 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
> +                        tint = Color.Unspecified
p1: 이거 이미지 웃고 있는 아이가 아니라 체크표시로 바꿔주세용

2024-11-27 13:08 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
> +        }
정성 미쳤도리ㅠ

2024-11-27 13:08 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
> +                Icon(
p2: 저같은 경우는 여러개의 아이템이 있을 때 spacedBy를 쓰고 있습니다! 반복된 간격을 가지는 경우가 아니라면 padding bottom을 줘서 위에서부터 내려오는 방식으로 사용할 것 같아요ㅎㅎ 그냥 제 방식일 뿐입니당근

2024-11-27 13:08 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/LocationSection.kt
> +            .padding(vertical = 24.dp)
p1:이 부분 실기기로 보니까 end 부분이 살짝 잘렸더라구용 수정 부탁드릴게요!

2024-11-27 13:08 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
> +}
p1: 이 부분 실기기로 돌려보니까 inner padding값 때문인지 아래에 공간이 좀 있더라구요. 말로는 한계가 있어서 영상 첨부하겠습니다!! inner padding 지워주시고 top 아래 부분 전체적으로 스크롤되게 해주시면 감사하겠습니다!!


https://github.com/user-attachments/assets/56116655-3790-4248-b13c-7bcf86fa168f

2024-11-28 07:12 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
> +                Icon(
생각해보니 블럭안에 3개로 늘어나면 추가 수정 가능성이 있을거 같아서 1~2개인 경우는 padding으로 관리하는것도 좋은 방법인거 같습니다!!

2024-11-28 07:42 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/LocationSection.kt
> +            .padding(vertical = 24.dp)
수정했습니다!! 근데 제 애뮬이랑 실기기에서는 수정 전에도 정상으로 보여서 한번만 확인 부탁드립니다!!🙏🏻

2024-11-28 07:43 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
> +}
헉 그러네요!! 수정 했습니다!!👍🏻🥕

2024-11-28 09:21 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
> +                        tint = Color.Unspecified
추가했습니다!

2024-11-28 09:50 UTC, angryPodo approved these changes
고생했당근!!!! 스트링 추출할때 단축키있으니까 호다닥 해버리자!(알고있었다면 죄송,,,)

2024-11-28 09:50 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
> +    var isDialogVisible by remember { mutableStateOf(false) }
p5: rememberSaveable요걸로 바꿔주면 좋을듯합니다!

2024-11-28 09:50 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/BadgeSection.kt
> +                text = "활동 뱃지 17개",
p4: 요거 alt + enter누르면 string추출 기능 있더라구요? 저는 몰랐음...

2024-11-28 09:50 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/SellerProfileSection.kt
> +                            )
미친 디테일...👍

2024-11-28 11:12 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/LocationSection.kt
> +            .padding(vertical = 24.dp)
이제 안잘리고 잘 보이네용 ㅎㅎ

2024-11-28 11:12 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
> +}
확인ㅋ

2024-11-28 11:14 UTC, hyoeunjoo approved these changes
굿!! 완벽하다능!! 기기대응도 잘된당근!!!! 머지하세요!
컨플릭 해결 안되면 부르구!!

2024-11-28 11:34 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/component/section/BadgeSection.kt
> +                text = "활동 뱃지 17개",
저도 덕분에 알았슴다 ㅋㅋㅋㅋㅌ 👍🏻

2024-11-28 11:36 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/sellerProfile/SellerProfileScreen.kt
> +    var isDialogVisible by remember { mutableStateOf(false) }
넵! 추후 viewmodel 적용하면서 리펙해보겠습니다!

2024-11-28 11:48 UTC, merged