[Feat/#25] 상품 상세 페이지 서버 통신 구현
SOPT-all/35-COLLABORATION-ANDROID-DAANGN pull request #28
Opened 2024-11-28 21:03 UTC by angryPodo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #25 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- 아키텍쳐 패턴 잘 적용하기
- User,Product api 분리하기

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/241a051f-fc15-4b9a-ac0f-c3a5a363a1d7

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
이전 브랜치에서 혼 많이 나고 적용했는데 그래도!!!! 이상하거나 부족한점 있으시면 말씀해주세요!!!!!

2024-11-28 21:30 UTC, hyoeunjoo requested changes
스폰지세요? 쫙쫙 빨아당기네!!! 고생했당근!! 고지가 코앞이야~~~

2024-11-28 21:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/data/mapper/ProductDetailMapper.kt
> +    productId = productId,
p2:요거는 네이밍을 모두 toModel로 정하신 이유가 있을까용?

2024-11-28 21:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/data/model/response/ResponseProductInfoDto.kt
>      @SerialName("title")
굿굿 ㅋㅋ

2024-11-28 21:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailViewModel.kt
> +    )
p2: 이 부분은 그냥 데이터들을 담는 용도로 사용되는 것 같은데 클래스명이 State인 이유가 있을까용?
또한 구조상 model패키지 안에 있어도 좋을 것 같다는 생각이 들어용!

2024-11-28 21:30 UTC, hyoeunjoo commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailViewModel.kt
> +            }
p2: try catch도 좋지만 onSuccess, onFailure도 있다능!! 그 구조가 조금 더 직관적이고 보기 편한 것 같아용! (제안)

2024-11-28 21:49 UTC, wjdrjs00 approved these changes
고생하셨습니다!! 저번 리뷰도 반영 많이 해줘서 👍🏻🙇🏻‍♂️
이번에는 간단한 수정정도만 있는거 같습니다!! 이제 진짜 거의 끄읏~!

2024-11-28 21:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/data/mapper/ProductDetailMapper.kt
> +internal fun ResponseProductInfoDto.toModel() = ProductDetailModel(
p1: internal 가시성은 제거해주셔도 될거같습니다! (지금 프로젝트가 싱글(단일)모듈이라 의미가 없을거 같기 때문입니다!!)
(추가로 다른 매핑메소드에도 동일하게 적용되는 리뷰입니다!!)

p1: 추가로 model을 제거하면 `ResponseProductInfoDto.toProductDetail() = ProductDetailModel( ...` 이렇게 할 수 있을거 같습니다!! (다른 매핑메소드도 동일하게 적용될거 같아요!!)

2024-11-28 21:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/domain/model/ProductDetail.kt
> +data class ProductDetailModel(
p1: 저번 리뷰와 같은 이유로 Model 명시 제거 부탁드립니다!! 다른 도메인 모델에도 동일하게 적용 부탁드립니다!!🙇🏻‍♂️🙇🏻‍♂️
```suggestion
data class ProductDetail(
```

2024-11-28 21:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/domain/model/ProductDetail.kt
> +data class RelatedProductModel(
p1: 요기도
```suggestion
data class RelatedProduct(
```

2024-11-28 21:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/domain/model/User.kt
> +data class UserDetailModel(
p1: 요기도🙇🏻‍♂️
```suggestion
data class UserDetail(
```

2024-11-28 21:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailScreen.kt
> +        targetValue = if (isScrolledPastImage) Color.White else Color.White.copy(alpha = 0f),
p5: 👍🏻👍🏻👍🏻

2024-11-28 21:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/carrot/presentation/productDetailScreen/ProductDetailViewModel.kt
>  }
p1: DetailState는 중첩 클래스보다 따로 빼주는게 좋을거 같습니다!
```suggestion
class ProductDetailViewModel(
    private val productRepository: ProductDetailRepository,
    private val userRepository: UserRepository
) : ViewModel() {
    private val _uiState = MutableStateFlow<UiState<DetailState>>(UiState.Loading)
    val uiState: StateFlow<UiState<DetailState>> = _uiState.asStateFlow()

    fun fetchProductDetail(productId: Long, userId: Long) {
        viewModelScope.launch {
            _uiState.value = UiState.Loading
            try {
                val productInfo = productRepository.getProductInfo(productId).getOrThrow()
                val userInfo = userRepository.getUserInfo(userId).getOrThrow()
                val relatedProducts = productRepository.getSellingProducts(userId).getOrThrow()

                _uiState.value = UiState.Success(DetailState(productInfo, userInfo, relatedProducts))
            } catch (e: Exception) {
                e.printStackTrace()
                _uiState.value = UiState.Error(e.message)
            }
        }
    }
}

data class DetailState(
    val productInfo: ProductDetailModel,
    val userInfo: UserDetailModel,
    val relatedProducts: List<RelatedProductModel>
)

```

2024-11-29 02:32 UTC, angryPodo commented on app/src/main/java/org/sopt/carrot/domain/model/ProductDetail.kt
> +data class ProductDetailModel(
파일이름만 바꾸고 요건 수정안했네요ㅠ 적용했습니다!

2024-11-29 02:56 UTC, hyoeunjoo approved these changes
그에게 주어지는 어푸목걸이....

2024-11-29 02:58 UTC, merged